#!/usr/bin/env python3
"""Generate the SupraMAS DSH bundle patches from the role-contract Markdown files.

`packages/supramas-dsh/agents/*.md` are the single source of truth for role
contracts. Two patch files are generated from them, because the two consumers
select their toolset differently:

* `cordis.patch.yml` — profile-level rows. This is what `dsh --profile headless
  --patch ...` loads, and the headless profile has no preset registry, so the
  delegation roles have to be global there.
* `presets/materials-research.patch.yml` — one `@deepseek-ai/dsh-agent-preset`
  declaration. A preset declares the *complete* toolset for its sessions, so this
  file also carries the standard research roster (bash/fs/skills/web/...), a
  materials-research persona, and the same delegation roles.

Contracts are inlined as YAML literal blocks rather than read through `!!js`
expressions: inlining keeps each patch self-contained, independent of the process
working directory, and verifiable without booting an agent.

Usage:
    PYTHONDONTWRITEBYTECODE=1 python3 scripts/build_supramas_patch.py          # write
    PYTHONDONTWRITEBYTECODE=1 python3 scripts/build_supramas_patch.py --check  # verify
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
BUNDLE_DIR = REPO_ROOT / "packages" / "supramas-dsh"
AGENTS_DIR = BUNDLE_DIR / "agents"
PATCH_PATH = BUNDLE_DIR / "cordis.patch.yml"
PRESET_PATH = BUNDLE_DIR / "presets" / "materials-research.patch.yml"

TOOL_SUBAGENT = "@deepseek-ai/dsh-tool-subagent"

PRESET_ID = "materials-research"
PRESET_NAME = "材料学科研"

# codex role file stem -> (DSH tool name, extra config lines)
#
# maxDepth bounds the *caller's* reachable delegation depth, so 0 would make the
# tool uncallable ("subagent depth 1 exceeds maxDepth 0"). 1 lets the main-session
# coordinator delegate while stopping the child from delegating further.
#
# toolFilter denials must name tools the harness actually has: tools.restrict()
# fails the whole registration on an unknown global tool name.
ROLES: dict[str, dict] = {
    "strategy-builder-agent": {
        "tool_name": "strategy_builder",
        "extra": {"backgroundMode": "continuable", "maxDepth": 1},
    },
    "strategy-tree-reviewer": {
        "tool_name": "strategy_reviewer",
        "extra": {
            "backgroundMode": "continuable",
            "maxDepth": 1,
            "toolFilter": {"deny": ["write", "edit"]},
        },
    },
    "idea-expert-agent": {
        "tool_name": "idea_expert",
        "extra": {"backgroundMode": "continuable", "maxDepth": 1},
    },
    "idea-review-agent": {
        "tool_name": "idea_review",
        "extra": {
            "backgroundMode": "continuable",
            "maxDepth": 1,
            "toolFilter": {"deny": ["write", "edit"]},
        },
    },
    "idea-proximity-agent": {
        "tool_name": "idea_proximity",
        "extra": {"backgroundMode": "continuable", "maxDepth": 1},
    },
    "idea-ranking-agent": {
        "tool_name": "idea_ranking",
        "extra": {"backgroundMode": "continuable", "maxDepth": 1},
    },
    "idea-evolution-agent": {
        "tool_name": "idea_evolution",
        "extra": {"backgroundMode": "continuable", "maxDepth": 1},
    },
}

GLOBAL_HEADER = """\
# GENERATED by scripts/build_supramas_patch.py -- do not edit by hand.
#
# Profile-level SupraMAS rows: the delegation roles are registered globally so
# that a session without the materials-research preset can still delegate. Load
# it against a profile with:
#     dsh --profile headless --patch packages/supramas-dsh/cordis.patch.yml "<task>"
#
# The GUI equivalent is the preset in presets/materials-research.patch.yml.
"""

PRESET_HEADER = """\
# GENERATED by scripts/build_supramas_patch.py -- do not edit by hand.
#
# `材料学科研` agent preset: select it in a session (General settings -> agent
# preset) to run with a materials-research persona and the SupraMAS delegation
# roles. A preset declares the complete toolset for its sessions, so this file
# carries the research roster as well.
"""

PERSONA = """\
You are a materials science research agent working on high-temperature
superconductors, especially REBCO coated conductors, thin films, and flux
pinning.

You build literature-grounded knowledge rather than recalling it: every strategy
claim you make must trace to a paper chunk saved under the run's `papers_dir`.
When evidence is thin, say so and record the gap instead of filling it in.

Prefer the project's own workflows over ad-hoc scripting. Load the
`supramas-project-contract` skill for the execution model, roles, and stage
workflows; keep `runs/{job_id}/tree_state.json` current; and delegate node
construction and review to the role tools instead of doing both sides yourself.
"""

# `supramas-skills` mounts this bundle's own `lib/index.js`, whose `apply()`
# registers `assets/skills/` with the harness and appends the absolute
# `assets/tools/` paths to each skill body.
#
# The research roster. Modeled on the shipped `standard` preset so that the tool
# catalog stays complete; plan mode and the workflow engine are intentionally
# omitted because a research run does not use them.
#
# A preset must declare TOOLS, not the singleton SERVICES the parent scope already
# provides: re-declaring `dsh-jobs-local` or `dsh-goal` inside a preset fails the
# whole preset with "service X has been registered at <...>". That is why
# `tool-jobs`/`command-goal`/`tool-goal` are here but `jobs`/`goal` are not.
PRESET_ROSTER = """\
          - id: persona
            name: '@deepseek-ai/dsh-persona'
            config:
              suffix: Your working directory is {{cwd}}.
              prefix: |
@@PERSONA@@
          - id: agent-instructions
            name: '@deepseek-ai/dsh-agent-instructions'
            config:
              maxBytes: 65536
          - id: tool-bash
            name: '@deepseek-ai/dsh-tool-bash'
            disabled: !!js process.platform === 'win32'
          - id: tool-pwsh
            name: '@deepseek-ai/dsh-tool-pwsh'
            disabled: !!js process.platform !== 'win32'
          - id: tool-fs
            name: '@deepseek-ai/dsh-tool-fs'
          - id: tool-fs-search
            name: '@deepseek-ai/dsh-tool-fs-search'
            config:
              sampleOverCapGlobResults: false
          - id: tool-jobs
            name: '@deepseek-ai/dsh-tool-jobs'
          - id: skill-filesystem
            name: '@deepseek-ai/dsh-skill-filesystem'
          - id: tool-skill
            name: '@deepseek-ai/dsh-tool-skill'
          - id: supramas-skills
            name: 'supramas-dsh'
          - id: command-goal
            name: '@deepseek-ai/dsh-command-goal'
          - id: tool-goal
            name: '@deepseek-ai/dsh-tool-goal'
          - id: tool-ask-user
            name: '@deepseek-ai/dsh-tool-ask-user'
          - id: tool-todo
            name: '@deepseek-ai/dsh-tool-todo'
            config:
              allowParallelInProgress: true
          - id: tool-web
            name: '@deepseek-ai/dsh-tool-web'
            config:
              fetch: true
              searchTimeoutMs: 60000
          - id: present
            name: '@deepseek-ai/dsh-tool-present'
          - id: compaction
            name: cordis:group
            group: true
            isolate:
              compaction: true
              toolResultPruner: true
            config:
              - id: compaction-basic
                name: '@deepseek-ai/dsh-compaction-basic'
              - id: command-compact
                name: '@deepseek-ai/dsh-command-compact'
              - id: tool-result-pruner
                name: '@deepseek-ai/dsh-compaction-tool-result-pruner'
                config:
                  thresholdChars: 8192
                  headChars: 4096
                  tailChars: 1024
          - id: delegation
            name: cordis:group
            group: true
            isolate:
              workflowEngine: false
            config:
              - id: tool-subagent-control
                name: '@deepseek-ai/dsh-tool-subagent-control'
              - id: tool-subagent-list-agents
                name: '@deepseek-ai/dsh-tool-subagent-control/list-agents'
              - id: tool-subagent
                name: '@deepseek-ai/dsh-tool-subagent'
                config:
                  provider: spawn
                  toolName: subagent
                  backgroundMode: continuable
@@ROLES@@"""


def read_persona(path: Path) -> str:
    """Return the contract body with its YAML frontmatter removed."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            text = text[end + 4 :]
    return text.strip("\n")


def indent_block(text: str, spaces: int) -> str:
    pad = " " * spaces
    return "\n".join((pad + line) if line.strip() else "" for line in text.splitlines())


def render_role(stem: str, spec: dict, indent: int = 4) -> str:
    """Render one `dsh-tool-subagent` row at the given dash indent."""
    persona_path = AGENTS_DIR / f"{stem}.md"
    if not persona_path.is_file():
        raise SystemExit(f"missing role contract: {persona_path}")
    persona = read_persona(persona_path)

    key = " " * (indent + 2)
    value = " " * (indent + 4)
    lines = [
        f"{' ' * indent}- id: tool-subagent-{spec['tool_name']}",
        f"{key}name: '{TOOL_SUBAGENT}'",
        f"{key}config:",
        f"{value}provider: spawn",
        f"{value}toolName: {spec['tool_name']}",
    ]
    for config_key, config_value in spec["extra"].items():
        if isinstance(config_value, dict):
            lines.append(f"{value}{config_key}:")
            for sub_key, sub_value in config_value.items():
                rendered = "[" + ", ".join(f"'{item}'" for item in sub_value) + "]"
                lines.append(f"{value}  {sub_key}: {rendered}")
        else:
            lines.append(f"{value}{config_key}: {config_value}")
    lines.append(f"{value}persona: |")
    lines.append(indent_block(persona, indent + 6))
    return "\n".join(lines) + "\n"


def ordered_roles() -> list[tuple[str, dict]]:
    """Strategy roles first so the generated file reads in pipeline order."""
    stems = list(ROLES)
    stems.sort(key=lambda stem: (not stem.startswith("strategy-"), list(ROLES).index(stem)))
    return [(stem, ROLES[stem]) for stem in stems]


def build_global_patch() -> str:
    parts = [GLOBAL_HEADER, "- insert:\n"]
    for stem, spec in ordered_roles():
        parts.append(render_role(stem, spec, indent=4))
    return "\n".join(parts)


def build_preset_patch() -> str:
    roles = "\n".join(render_role(stem, spec, indent=14) for stem, spec in ordered_roles())
    # Deliberately not str.format(): the roster carries DSH template placeholders
    # such as {{cwd}}, and format() would collapse them to {cwd}.
    roster = PRESET_ROSTER.replace(
        "@@PERSONA@@", indent_block(PERSONA.strip("\n"), 16)
    ).replace("@@ROLES@@", roles)
    return "\n".join(
        [
            PRESET_HEADER,
            "- insert:",
            "    - id: preset-materials-research",
            "      name: '@deepseek-ai/dsh-agent-preset'",
            "      config:",
            f"        id: {PRESET_ID}",
            f"        name: {PRESET_NAME}",
            "        description: 面向材料科学的文献策略树挖掘与证据可追溯的 idea 设计（REBCO 磁通钉扎）。",
            "        order: 10",
            "        plugins:",
            roster.rstrip("\n"),
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Verify instead of writing.")
    args = parser.parse_args()

    if not AGENTS_DIR.is_dir():
        print(f"agents directory not found: {AGENTS_DIR}", file=sys.stderr)
        return 1

    generated = {
        PATCH_PATH: build_global_patch(),
        PRESET_PATH: build_preset_patch(),
    }

    if args.check:
        stale = [
            str(path)
            for path, content in generated.items()
            if not path.exists() or path.read_text(encoding="utf-8") != content
        ]
        if stale:
            print("out of date:\n  " + "\n  ".join(stale), file=sys.stderr)
            return 1
        print(f"up to date: {len(generated)} patches, {len(ROLES)} roles")
        return 0

    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
